CREATE TABLE News (
  id NUMBER(20) NOT NULL,
  short_text VARCHAR2(100) NOT NULL,
  full_text VARCHAR2(2000) NOT NULL,
  title VARCHAR2(30) NOT NULL,
  creation_date TIMESTAMP NOT NULL,
  modification_date DATE NOT NULL
  CONSTRAINT "news_id" PRIMARY KEY (id)
);

CREATE SEQUENCE AUTO_INCREMENT_NEWS_ID
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE OR REPLACE TRIGGER T_NEWS_ID
BEFORE INSERT
ON News
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.id is null) then
  SELECT AUTO_INCREMENT_NEWS_ID.nextval
  INTO :new.id
  FROM dual;
  end if;
END;
/

ALTER TRIGGER "T_NEWS_ID" ENABLE;